
/**
 * \file            operator_utils.c
 * \brief           Operator related functions
 */

/*
 * Copyright (c) 2020 Tilen MAJERLE
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * This file is part of LwGSM - Lightweight GSM-AT library.
 *
 * Author:          Rafael de la Rosa <derosa.rafael@gmail.com>
 * Version:         v0.1.0
 */


#include <string.h>
#include "operator_utils.h"

static const char* netact_str[] = {
    "LWGSM_USER_SPEC_GSM",
    "LWGSM_COMPACT_GSM",
    "LWGSM_EGPRS_GSM",
    "LWGSM_USER_SPEC_LTE_M1_A_GB",
    "LWGSM_USER_SPEC_LTE_NB_S1"
};

/// @brief Print data sended in event data generated by COPS scan
/// @param evt      The event struc
/// @retval lwgsmOK on success, member of \ref lwgsmr_t enumeration otherwise
lwgsmr_t operator_utils_print_scan(lwgsm_evt_t* evt){

    if(evt->type != LWGSM_EVT_OPERATOR_SCAN){
        return lwgsmPARERR;
    }

    if(evt->evt.operator_scan.res != lwgsmOK){
        printf("Operator scanning not suceed. Code error: %d\r\n", evt->evt.operator_scan.res);
        return lwgsmERR;
    }

    printf("======= OPERATORS FOUND: %d =======\r\n", evt->evt.operator_scan.opf);
    for(int i=0; i<evt->evt.operator_scan.opf; i++){
        if(strcmp(evt->evt.operator_scan.ops[i].long_name, "") !=  0){
            printf("\t %d. %s\r\n", i+1, evt->evt.operator_scan.ops[i].long_name);
        }else{
            printf("\t %d. %s\r\n", i+1, "NAME NOT SPECIFIED");
        }
        printf("\t\t - Status: %d \r\n", evt->evt.operator_scan.ops[i].stat);
        printf("\t\t - Numeric value: %d \r\n", evt->evt.operator_scan.ops[i].num);
        printf("\t\t - Technology: %s (%d) \r\n", netact_str[evt->evt.operator_scan.ops[i].netact], evt->evt.operator_scan.ops[i].netact);
    }

    return lwgsmOK;
}